### ISSUE TITLE
Rules that fail with a (technical) exceptions should be reported as Open instead of Fail

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-ios#5]
## Describe the bug

When a rule fails with a (technical) exception instead of returning true/false, the rule is reported as `fail`:
https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/a478f350183b467929450966d5a2cf7599bdff4d/Sources/CertLogic/CertLogic.swift#L71

## Expected behaviour

It should be reported as `open`.

## Steps to reproduce the issue

look at the code

## Technical details

n/a

## Possible Fix

see expected behavior

## Additional context

n/a

**Comment by alexchornyi** [comment]
@SchulzeStTSI need to discuss and make the same in Android part.

**Comment by alexchornyi** [comment]
fixed in #17

**Comment by mlenkeit** [comment]
@alexchornyi  I think this is not fixed yet:

https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/blob/76244f850a740d0031dc7e61eb9af48229c8d0a9/Sources/CertLogic/CertLogic.swift#L65-L67

When an exception is thrown from CertLogic/JsonLogic (that's the _technical exception_ I was referring to), it's still mapped to `fail` instead of `open`. In a discussion with @SchulzeStTSI, we understood that a technical exception should map to `open`.

**Comment by alexchornyi** [comment]
@mlenkeit fixed on #18

**Comment by mlenkeit** [comment]
LGTM
